name: Build Binaries for amd64
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version to build (eg: 4.4.1)'
        required: true
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: containers/podman
          ref: v${{ inputs.version }}
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install \
          btrfs-progs \
          dpkg \
          git \
          golang-go \
          go-md2man \
          iptables \
          libassuan-dev \
          libbtrfs-dev \
          libc6-dev \
          libdevmapper-dev \
          libglib2.0-dev \
          libgpgme-dev \
          libgpg-error-dev \
          libprotobuf-dev \
          libprotobuf-c-dev \
          libseccomp-dev \
          libselinux1-dev \
          libsystemd-dev \
          pkg-config \
          runc \
          uidmap
      - name: Build binaries
        env:
          VERSION: ${{ inputs.version }}
        run: |
          make BUILDTAGS="seccomp"
          sudo make podman-release
          tar -xvf podman-release-amd64.tar.gz
          mv podman-v$VERSION podman_$VERSION-1_amd64 
          mkdir podman_$VERSION-1_amd64/DEBIAN
          touch podman_$VERSION-1_amd64/DEBIAN/control
          cat << EOT >> podman_$VERSION-1_amd64/DEBIAN/control
          Package: podman
          Version: $VERSION
          Architecture: amd64
          Maintainer: podman.io <podman@lists.podman.io>
          Description: Podman is a daemonless container engine for developing, managing, and running OCI Containers on your Linux System. 
          EOT
          dpkg-deb --build --root-owner-group podman_$VERSION-1_amd64
#      - uses: actions/upload-artifact@v3
#        with:
#          name: podman-release
#          path: ./podman-*.tar.gz
#      - uses: actions/upload-artifact@v3
#        with:
#          name: podman-release
#          path: ./podman_*.deb
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ inputs.version }}"
          prerelease: true
          files: |
            ./podman-*.tar.gz
            ./podman_*.deb
